name: 'Verify an NPM release'
description: 'Fetches a package from NPM and does some basic smoke tests'

inputs:
  npm-package:
    description: 'NPM Package'
    required: true
    default: '@google/gemini-cli@latest'
  expected-version:
    description: 'Expected version'
    required: true
  gemini_api_key:
    description: 'The API key for running integration tests.'
    required: true
  ref:
    description: 'The branch, tag, or SHA to release from.'
    required: false
    type: 'string'
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: '📝 Print Inputs'
      shell: 'bash'
      run: 'echo "${{ toJSON(inputs) }}"'

    - name: 'Checkout'
      uses: 'actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955' # ratchet:actions/checkout@v4
      with:
        path: 'verify'
        ref: '${{ github.event.inputs.ref }}'
        fetch-depth: 0

    - name: 'Install dependencies'
      shell: 'bash'
      working-directory: './verify'
      run: 'npm ci'

    - name: 'Build packages from source'
      shell: 'bash'
      working-directory: './verify'
      run: 'npm run build'

    - name: 'Install CLI globally from local build'
      shell: 'bash'
      working-directory: './verify'
      run: 'npm install -g ./packages/cli'

    - name: '🔬 Run integration tests against NPM release'
      working-directory: './verify'
      env:
        GEMINI_API_KEY: '${{ inputs.gemini_api_key }}'
        INTEGRATION_TEST_USE_INSTALLED_GEMINI: 'true'
        VERBOSE: 'true'
        DEBUG: 'true'
      shell: 'bash'
      run: 'npm run test:integration:sandbox:none -- integration-tests/ctrl-c-exit.test.ts'
